use_frameworks!

platform :ios, '8.0'

target 'NYLBluetooth_Example' do
  pod 'NYLBluetooth', :path => '../'
  pod 'Toast', '3.1.0'
  target 'NYLBluetooth_Tests' do
    inherit! :search_paths

    
  end
end
